FROM openjdk:17-alpine

ARG MONGO_USER
ARG MONGO_PASSWORD
ARG MONGO_HOST
ARG MONGO_PORT
ARG KAFKA_BROKER_HOST
ARG KAFKA_USER
ARG KAFKA_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG APP_NAME
ARG EMAIL_REQUEST_TOPIC_SINGLE="email-request-single"
ARG EMAIL_REQUEST_TOPIC_BATCH="email-request-batch"
ARG EMAIL_REQUEST_TOPIC_SANDBOX="email-request-sandbox"
ARG EMAIL_REQUEST_TOPIC_MULTIRCPT="email-request-multircpt"
ARG SPRING_PROFILE
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY

ENV BASE_DIR=${APP_NAME}
ENV MONGO_USER=${MONGO_USER}
ENV MONGO_PASSWORD=${MONGO_PASSWORD}
ENV MONGO_HOST=${MONGO_HOST}
ENV MONGO_PORT=${MONGO_PORT}
ENV KAFKA_BROKER_HOST=${KAFKA_BROKER_HOST}
ENV KAFKA_USER=${KAFKA_USER}
ENV KAFKA_PASSWORD=${KAFKA_PASSWORD}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV EMAIL_REQUEST_TOPIC_SINGLE=${EMAIL_REQUEST_TOPIC_SINGLE}
ENV EMAIL_REQUEST_TOPIC_BATCH=${EMAIL_REQUEST_TOPIC_BATCH}
ENV EMAIL_REQUEST_TOPIC_SANDBOX=${EMAIL_REQUEST_TOPIC_SANDBOX}
ENV EMAIL_REQUEST_TOPIC_MULTIRCPT=${EMAIL_REQUEST_TOPIC_MULTIRCPT}
ENV SPRING_PROFILE=${SPRING_PROFILE}
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}

COPY build/libs/emailapp-0.0.1.jar /${BASE_DIR}/

RUN apk update && apk upgrade && \
    apk add --no-cache ca-certificates

WORKDIR /${BASE_DIR}

EXPOSE 8080

CMD ["java", "-jar", "emailapp-0.0.1.jar"]