FROM openjdk:17-alpine

ARG MONGO_USER
ARG MONGO_PASSWORD
ARG MONGO_HOST
ARG MONGO_PORT
ARG KAFKA_BROKER_HOST
ARG APP_NAME

ENV BASE_DIR=${APP_NAME}
ENV MONGO_USER=${MONGO_USER}
ENV MONGO_PASSWORD=${MONGO_PASSWORD}
ENV MONGO_HOST=${MONGO_HOST}
ENV MONGO_PORT=${MONGO_PORT}
ENV KAFKA_BROKER_HOST=${KAFKA_BROKER_HOST}

COPY build/libs/emailapp-0.0.1.jar /${BASE_DIR}/

RUN apk update && apk upgrade

WORKDIR /${BASE_DIR}

EXPOSE 8080

CMD ["java", "-jar", "emailapp-0.0.1.jar"]
